FROM node:lts-alpine3.12 AS builder
WORKDIR /app
COPY . .
ARG OG_IMAGE_SECRET_KEY
ENV OG_IMAGE_SECRET_KEY=$OG_IMAGE_SECRET_KEY
RUN npm ci
RUN npm run build

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]
